services:
  ctfd:
    image: ctfd/ctfd:latest
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=NIMG8CROpUvOv4opqHLdTg6kHuRqwAgI
      - UPLOAD_FOLDER=/var/uploads
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
    networks:
        default:
        internal:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        internal:

networks:
    default:
    internal:
        internal: true

